version: '3'
services:
  web:
    build:
      context: .
      dockerfile: etc/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - ./app:/var/www/html/

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test-password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: